### ISSUE TITLE
Help wanted: why does the README not appear

### ISSUE THREAD

**Issue by alexec** [helm/hub#151]
For other charts, READMEs appear, but not for Argo, e.g.:

https://hub.helm.sh/charts/argo/argo-cd/0.5.2

Here is the template:

https://github.com/argoproj/argo-helm/tree/master/charts/argo-cd

**Comment by andresmgot** [comment]
Hi @alexec, I checked that issue with Kubeapps (in which the issue is also present). It seems a problem with the way the tarball is packaged. The service extracting the README is failing to do so. When I try to extract the tarballs for argo I get several warnings which doesn't appear for other charts:

```
▶ tar zxf argo-0.5.2.tgz 
tar: Ignoring unknown extended header keyword 'LIBARCHIVE.creationtime'
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
...
```

Maybe there is an issue with the packaging procedure?

**Comment by mattfarina** [comment]
@alexec I concur with @andresmgot on this. The Helm Hub extracts the `README.md` from the archive. It's not able to do that which is why it can't display.

On Mac I cannot reproduce what he found but I can on Linux.

I suspect the problem is with the publish.sh script. Instead of using `tar` to create the archive might I suggest using the `helm package` command.

**Comment by alexec** [comment]
OK. I've updated the script:

https://github.com/argoproj/argo-helm/blob/master/scripts/publish.sh#L11

**Comment by alexec** [comment]
Hmm.. still does not work?

Version 0.5.4 should have README.
https://hub.helm.sh/charts/argo/argo-cd

**Comment by prydonius** [comment]
I'm still seeing the unknown extended header error when extracting on Linux... looks like this might be an issue when creating tar archives on macOS: http://lifeonubuntu.com/tar-errors-ignoring-unknown-extended-header-keyword/.

What platform does your packaging script run on?

Based on that article, Monocular/Kubeapps should just ignore the warnings and extract the README anyway.

**Comment by alexec** [comment]
Mac. Run on Docker maybe?

**Comment by alexec** [comment]
Could error be red herring?

**Comment by andresmgot** [comment]
ah, I think I've found the issue. The problem is not related to the headers warning. The issue is that your tarball doesn't contain a folder (all the files are in the root). It's expected to have a folder with all the files within it. Instead of `./README.md`, it should be located at `argo/README.md`.

**Comment by alexec** [comment]
Note to self: 0.1.4 should be updated https://hub.helm.sh/charts/argo/argo-ci

**Comment by liwenhe1993** [comment]
On Linux I use the `helm package` command.The README not appear.

**Comment by andresmgot** [comment]
I think that your case @liwenhe1993 is different because I am able to see the README in https://hub.kubeapps.com/charts/liwenhe1993/clickhouse (so I am not sure why it's failing for the helm hub).
